# Generated by Django 5.1.2 on 2024-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit1', models.CharField(max_length=100)),
                ('fruit2', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
